### ISSUE TITLE
Test URL does not work out-of-the-box and what looks like credentials are stored in views.py

### ISSUE THREAD

**Issue by ctrowat** [sjm-steffann/netbox-vcenter#1]
As provided, the plugin has a "Test" URL that does not function for the vast majority of us, and the view it uses also contains hard-coded credentials for a vcenter that pings, but does not present a login page:

https://github.com/sjm-steffann/netbox-vcenter/commit/b61d6f3d344f00f8b8ff69ad8f1afb0428203730#diff-302937711771608eb1c6ef167027ae46R105

It might be better if the test view was either removed, or was configurable in some manner to make it useful for people testing this plugin.

**Comment by steffann** [comment]
Thanks for notifying me! That code should never have been committed. Luckily that is an old password that doesn't work anyway :)

**Comment by steffann** [comment]
Stupid… I actually changed that a long time ago but forgot to push it to GitHub. My apologies!
